### ISSUE TITLE
Could not deserialize key data

### ISSUE THREAD

**Issue by torvald** [machine-learning-apps/actions-app-token#3]
So i believe done what the README says, at least decoding the value with base64 gives me my original file and there are no newlines present in either the base64 encoded text, nor in the secret. The pem i starting and ending with `-----BEGIN OPENSSH PRIVATE KEY-----`, `-----END OPENSSH PRIVATE KEY-----`.

Is this a known issue?

```
  with:
    APP_PEM: ***
    APP_ID: ***
/usr/bin/docker run --name hamelsmuapptoken_c4112e --label 8118cb --workdir /github/workspace --rm -e INPUT_APP_PEM -e INPUT_APP_ID -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_DEBUG -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/platform/platform":"/github/workspace" hamelsmu/app-token
Traceback (most recent call last):
  File "/app/token_getter.py", line 147, in <module>
    id = app.get_installation_id()
  File "/app/token_getter.py", line 87, in get_installation_id
    headers = ***'Authorization': f'Bearer ***self.get_jwt().decode()***',
  File "/app/token_getter.py", line 77, in get_jwt
    private_key = default_backend().load_pem_private_key(key_file.read(), None)
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1045, in load_pem_private_key
    password,
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1271, in _load_key
    self._handle_key_loading_error()
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1329, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
```

**Comment by torvald** [comment]
I created a new key and that worked, I must somehow have messed up the key content. Sorry. (-:
